compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

packageExtensions:
  "@stylexjs/babel-plugin@*":
    dependencies:
      "@babel/core": ^7.19.6
      "@babel/traverse": ^7.0.0-0
      "@babel/types": ^7.15.6
      invariant: ^2.2.4
      postcss-value-parser: ^4.2.0
      styleq: ^0.1.3

yarnPath: .yarn/releases/yarn-4.1.1.cjs
